version: "3.8"
services:
  marry-me-redis:
    container_name: marry-me-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ycw92325/marry-me-redis
    ports:
      - "6379:6379"
  marry-me-database:
    container_name: marry-me-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ycw92325/marry-me-database
    environment:
      - MARIADB_DATABASE=marry-me
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"